# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dnakano <dnakano@student.42tokyo.jp>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/05 17:34:06 by dnakano           #+#    #+#              #
#    Updated: 2021/02/10 07:58:14 by dnakano          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

TESTDIR		:=	./test

.PHONY:		all
all:		test

.PHONY:		test
test:
			make -C ./test test

.PHONY:		clean
clean:
			make -C ./test clean

.PHONY:		fclean
fclean:
			make -C ./test fclean

.PHONY:		re
re:
			make -C ./test re
